sudo: required

services:
  - docker

before_install:
  - docker build -t dockerTravis -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerTravis npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "Docker-Edu-Test"
  env: "Dockeredutest-env"
  bucket_name: "elasticbeanstalk-us-east-1-003716801716"
  bucket_path: "Docker-Edu-Test"
  on:
    all_branches: true